import Head from "next/head";
import LeftSide from "../components/LeftSide";
import style from '../styles/font.module.css'
import RightSide from "@/components/RightSide";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />

      </Head>
      <div className="min-h-screen">
        <div className="flex justify-center gap-4 py-12">
          <div className={`${style.boxShaddow} w-80 rounded-lg`}>
            <LeftSide></LeftSide>
          </div>
          <div className={`${style.boxShaddow} w-[900px] rounded-lg`}><RightSide></RightSide></div>
        </div>
      </div>
    </>
  );
}
